app/accounts/models.py
from datetime import datetime

from flask_login import UserMixin

from app import bcrypt, db


class User(UserMixin, db.Model):

    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    authProvider = db.Column(db.String, nullable=False, default="credentials")
    email = db.Column(db.String, unique=True, nullable=False)
    password = db.Column(db.String, nullable=False)
    username = db.Column(db.String, nullable = True)
    avatar_url = db.Column(db.String, nullable = True)
    created_on = db.Column(db.DateTime, nullable=False)
    is_admin = db.Column(db.Boolean, nullable=False, default=False)
    is_confirmed = db.Column(db.Boolean, nullable=False, default=False)
    confirmed_on = db.Column(db.DateTime, nullable=True)

    def __init__(self, *args, **kwargs):
        self.authProvider = kwargs.get("authProvider")
        self.email = kwargs.get("email")
        self.password = bcrypt.generate_password_hash(kwargs.get("password"))
        self.username = kwargs.get("username") or kwargs.get("email").split("@")[0]
        self.avatar_url = kwargs.get("avatar_url")
        self.created_on = datetime.now()
        self.is_admin = kwargs.get("is_admin")
        self.is_confirmed = kwargs.get("is_confirmed")
        self.confirmed_on = kwargs.get("confirmed_on")

        
    def __repr__(self):
        return f"<email {self.email}>"

app/accounts/forms.py
from flask_wtf import FlaskForm
from wtforms import EmailField, PasswordField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from app.accounts.models import User


class RegisterForm(FlaskForm):
    email = EmailField(
        "Email", validators=[DataRequired(), Email(message=None), Length(min=6, max=40)]
    )
    password = PasswordField(
        "Password", validators=[DataRequired(), Length(min=6, max=25)]
    )
    confirm = PasswordField(
        "Repeat password",
        validators=[
            DataRequired(),
            EqualTo("password", message="Passwords must match."),
        ],
    )

    def validate(self, extra_validators=None):
        initial_validation = super(RegisterForm, self).validate(extra_validators)
        if not initial_validation:
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append("Email already registered")
            return False
        if self.password.data != self.confirm.data:
            self.password.errors.append("Passwords must match")
            return False
        return True


class LoginForm(FlaskForm):
    email = EmailField("Email", validators=[DataRequired(), Email()])
    password = PasswordField("Password", validators=[DataRequired()])

app/accounts/views.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_user, current_user, logout_user, login_required
from datetime import datetime

from app import db, bcrypt, oauth, google
from app.accounts.models import User
from app.accounts.token import confirm_token, generate_token
from app.utils.decorators import logout_required
from app.utils.email import send_email

from .forms import RegisterForm, LoginForm

accounts_bp = Blueprint("accounts", __name__)

@accounts_bp.route("/register", methods=["GET", "POST"])
@logout_required
def register():
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = User(email=form.email.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()

        token = generate_token(user.email)
        confirm_url = url_for('accounts.confirm_email', token = token, _external = True)
        html = render_template('accounts/confirm_email.html', confirm_url = confirm_url)
        subject = "Please confirm your email"
        send_email(user.email, subject, html)

        login_user(user)

        flash("A confirmation email has been sent via email.", "success")
        return redirect(url_for("accounts.inactive"))

    return render_template("accounts/register.html", form=form)


@accounts_bp.route("/login", methods=["GET", "POST"])
@logout_required
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, request.form["password"]):
            login_user(user)
            return redirect(url_for("core.home"))
        else:
            flash("Invalid email or/and password", "danger")
            return render_template("accounts/login.html", form=form)
    return render_template("accounts/login.html", form=form)

@accounts_bp.route('/confirm/<token>')
@login_required
def confirm_email(token):
    if current_user.is_confirmed:
        flash('Account already confirmed', 'success')
    email = confirm_token(token)
    user = User.query.filter_by(email = current_user.email).first_or_404()
    if user.email == email:
        user.is_confirmed = True
        user.confirmed_on = datetime.now()
        db.session.add(user)
        db.session.commit()
        flash('You have confirmed your account. Thanks!', 'success')
    else:
        flash('The confirmation link is invalid or expired', 'danger')
    return redirect(url_for('core.home'))

@accounts_bp.route('/inactive')
@login_required
def inactive():
    if current_user.is_confirmed:
        return redirect(url_for('core.home'))
    return render_template('accounts/inactive.html')

@accounts_bp.route('/resend')
@login_required
def resend_confirmation():
    if current_user.is_confirmed:
        flash('Your account has already been confirmed.', 'success')
        return redirect(url_for('core.home'))
    token = generate_token(current_user.email)
    confirm_url = url_for('accounts.confirm_email', token = token, _external = True)
    html = render_template('accounts/confirm_email.html', confirm_url= confirm_url)
    subject = 'Please confirm your email'
    send_email(current_user.email, subject, html)
    flash('A new confirmation email has been sent.', 'success')
    return redirect(url_for('accounts.inactive'))

# Google OAuth
@accounts_bp.route('/auth/google')
@logout_required
def google_login():
    google_client = oauth.create_client("google")
    redirect_uri = url_for('accounts.google_auth', _external = True)
    return google_client.authorize_redirect(redirect_uri)

# todo: is the password hashed

@accounts_bp.route('/auth/google/callback')
@logout_required
def google_auth():
    google_client = oauth.create_client("google")
    token = google_client.authorize_access_token()
    resp = google_client.get('userinfo')
    user_info = resp.json()
    user = User.query.filter_by(email = user_info['email']).first()
    if user:
        login_user(user)
        return redirect(url_for('core.home'))
    else:
        user_dist = {
            'authProvider': 'google',
            'email': user_info['email'],
            'password': user_info['email'],
            'username': user_info['name'],
            'avatar_url': user_info['picture'],
            'is_admin': False,
            'is_confirmed': True,
            'confirmed_on': datetime.now()
        }
        user = User(**user_dist)
        db.session.add(user)
        db.session.commit()
        login_user(user)
        return redirect(url_for('core.home'))

@accounts_bp.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You were logged out", "success")
    return redirect(url_for("accounts.login"))

app/templates/accounts/confirm_email.html
<p>
  Welcome! Thanks for signing up. Please follow this link to activate your
  account:
</p>
<p><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>
<br />
<p>Cheers!</p>

app/templates/accounts/inactive.html
{% extends "base.html" %}
{% block content %}
  <div class="text-center">
    <h1>Welcome!</h1>
    <br />
    <p>
      You have not confirmed your account. Please check your inbox (and your
      spam folder) - you should have received an email with a confirmation link.
    </p>
    <p>
      Didn't get the email?
      <a href="{{ url_for('accounts.resend_confirmation') }}">Resend</a>.
    </p>
  </div>
{% endblock %}

app/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <main class="form-signin w-100 m-auto">
        <form role="form" method="post" action="">
          {{ form.csrf_token }}
          <h1 class="h3 mb-3 fw-normal text-center text-slate-300">
            Please sign in
          </h1>

          <div class="form-floating">
            {{ form.email(placeholder="email", class="form-control mb-2") }}
            {{ form.email.label }}
            {% if form.email.errors %}
              {% for error in form.email.errors %}
                <div class="alert alert-danger" role="alert">{{ error }}</div>
              {% endfor %}
            {% endif %}
          </div>
          <div class="form-floating">
            {{ form.password(placeholder="password", class="form-control mb-2") }}
            {{ form.password.label }}
            {% if form.password.errors %}
              {% for error in form.password.errors %}
                <div class="alert alert-danger" role="alert">{{ error }}</div>
              {% endfor %}
            {% endif %}
          </div>
          <button class="w-100 btn btn-lg btn-primary" type="submit">
            Sign in
          </button>
          <p class="text-center mt-3 text-slate-300">
            New User?
            <a href="{{ url_for('accounts.register') }}">Register now</a>
          </p>
        </form>
        <hr />
        {# google auth #}
        <div class="text-center m-auto">
          <a
            href="{{ url_for('accounts.google_login') }}"
            class="btn btn-lg btn-primary"
          >
            <i class="fab fa-google"></i> Sign up with Google
          </a>
        </div>
      </main>
    </div>
    <div class="col-md-4"></div>
  </div>
{% endblock %}

app/templates/accounts/register.html
{% extends "base.html" %}

{% block content %}
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <main class="form-signin w-100 m-auto">
        <form role="form" method="post" action="">
          {{ form.csrf_token }}
          <h1 class="h3 mb-3 fw-normal text-center text-slate-300 ">
            Please register
          </h1>

          <div class="form-floating">
            {{ form.email(placeholder="email", class="form-control mb-2") }}
            {{ form.email.label }}
            {% if form.email.errors %}
              {% for error in form.email.errors %}
                <div class="alert alert-danger" role="alert">{{ error }}</div>
              {% endfor %}
            {% endif %}
          </div>
          <div class="form-floating">
            {{ form.password(placeholder="password", class="form-control mb-2") }}
            {{ form.password.label }}
            {% if form.password.errors %}
              {% for error in form.password.errors %}
                <div class="alert alert-danger" role="alert">{{ error }}</div>
              {% endfor %}
            {% endif %}
          </div>
          <div class="form-floating">
            {{ form.confirm(placeholder="Confirm Password", class="form-control mb-2") }}
            {{ form.confirm.label }}
            {% if form.confirm.errors %}
              {% for error in form.confirm.errors %}
                <div class="alert alert-danger" role="alert">{{ error }}</div>
              {% endfor %}
            {% endif %}
          </div>
          <button class="w-100 btn btn-lg btn-primary" type="submit">
            Sign up
          </button>
          <p class="text-center mt-3 text-slate-300 ">
            Already registered?
            <a href="{{ url_for('accounts.login') }}">Login now</a>
          </p>
        </form>
        <hr />
        {# google auth #}
        <div class="text-center m-auto">
          <a
            href="{{ url_for('accounts.google_login') }}"
            class="btn btn-lg btn-primary"
          >
            <i class="fab fa-google"></i> Sign up with Google
          </a>
        </div>
      </main>
    </div>
    <div class="col-md-4"></div>
  </div>
{% endblock %}