app/accounts/views.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_user, current_user, logout_user, login_required
from datetime import datetime

from app import db, bcrypt, oauth, google
from app.accounts.models import User
from app.accounts.token import confirm_token, generate_token
from app.utils.decorators import logout_required
from app.utils.email import send_email

from .forms import RegisterForm, LoginForm

accounts_bp = Blueprint("accounts", __name__)

@accounts_bp.route("/register", methods=["GET", "POST"])
@logout_required
def register():
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        user = User(email=form.email.data, password=form.password.data)
        db.session.add(user)
        db.session.commit()

        token = generate_token(user.email)
        confirm_url = url_for('accounts.confirm_email', token = token, _external = True)
        html = render_template('accounts/confirm_email.html', confirm_url = confirm_url)
        subject = "Please confirm your email"
        send_email(user.email, subject, html)

        login_user(user)

        flash("A confirmation email has been sent via email.", "success")
        return redirect(url_for("accounts.inactive"))

    return render_template("accounts/register.html", form=form)


@accounts_bp.route("/login", methods=["GET", "POST"])
@logout_required
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, request.form["password"]):
            login_user(user)
            return redirect(url_for("core.home"))
        else:
            flash("Invalid email or/and password", "danger")
            return render_template("accounts/login.html", form=form)
    return render_template("accounts/login.html", form=form)

@accounts_bp.route('/confirm/<token>')
@login_required
def confirm_email(token):
    if current_user.is_confirmed:
        flash('Account already confirmed', 'success')
    email = confirm_token(token)
    user = User.query.filter_by(email = current_user.email).first_or_404()
    if user.email == email:
        user.is_confirmed = True
        user.confirmed_on = datetime.now()
        db.session.add(user)
        db.session.commit()
        flash('You have confirmed your account. Thanks!', 'success')
    else:
        flash('The confirmation link is invalid or expired', 'danger')
    return redirect(url_for('core.home'))

@accounts_bp.route('/inactive')
@login_required
def inactive():
    if current_user.is_confirmed:
        return redirect(url_for('core.home'))
    return render_template('accounts/inactive.html')

@accounts_bp.route('/resend')
@login_required
def resend_confirmation():
    if current_user.is_confirmed:
        flash('Your account has already been confirmed.', 'success')
        return redirect(url_for('core.home'))
    token = generate_token(current_user.email)
    confirm_url = url_for('accounts.confirm_email', token = token, _external = True)
    html = render_template('accounts/confirm_email.html', confirm_url= confirm_url)
    subject = 'Please confirm your email'
    send_email(current_user.email, subject, html)
    flash('A new confirmation email has been sent.', 'success')
    return redirect(url_for('accounts.inactive'))

# Google OAuth
@accounts_bp.route('/auth/google')
@logout_required
def google_login():
    google_client = oauth.create_client("google")
    redirect_uri = url_for('accounts.google_auth', _external = True)
    return google_client.authorize_redirect(redirect_uri)

# todo: is the password hashed

@accounts_bp.route('/auth/google/callback')
@logout_required
def google_auth():
    google_client = oauth.create_client("google")
    token = google_client.authorize_access_token()
    resp = google_client.get('userinfo')
    user_info = resp.json()
    user = User.query.filter_by(email = user_info['email']).first()
    if user:
        login_user(user)
        return redirect(url_for('core.home'))
    else:
        user_dist = {
            'authProvider': 'google',
            'email': user_info['email'],
            'password': user_info['email'],
            'username': user_info['name'],
            'avatar_url': user_info['picture'],
            'is_admin': False,
            'is_confirmed': True,
            'confirmed_on': datetime.now()
        }
        user = User(**user_dist)
        db.session.add(user)
        db.session.commit()
        login_user(user)
        return redirect(url_for('core.home'))

@accounts_bp.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You were logged out", "success")
    return redirect(url_for("accounts.login"))

app/core/views.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user

from app.utils.decorators import  check_is_confirmed

core_bp = Blueprint("core", __name__)


@core_bp.route("/")
@login_required
@check_is_confirmed
def home():
    return render_template("core/index.html")

app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Flask User Management</title>
    <!-- meta -->
    <meta name="description" content="" />
    <meta name="author" content="" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <!-- styles -->
    <!-- CSS only -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename="styles.css") }}"
    />
    {% block css %}{% endblock %}
  </head>
  <body class="bg-gray">
    {% include "navigation.html" %}

    <div class="container">
      <br />

      <!-- messages -->
      {% with messages = get_flashed_messages(with_categories=true) %}{% if messages %}
        <div class="row">
          <div class="col-md-4"></div>
          <div class="col-md-4">
            {% for category, message in messages %}
              <div
                class="alert alert-{{ category }} alert-dismissible fade show"
                role="alert"
              >
                {{ message }}
                <button
                  type="button"
                  class="btn-close"
                  data-bs-dismiss="alert"
                  aria-label="Close"
                ></button>
              </div>
            {% endfor %}
          </div>
          <div class="col-md-4"></div>
        </div>
      {% endif %}{% endwith %}

      <!-- child template -->
      {% block content %}{% endblock %}
    </div>

    <!-- scripts -->
    <script
      src="https://code.jquery.com/jquery-3.6.1.min.js"
      type="text/javascript"
    ></script>
    <!-- JavaScript Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
      crossorigin="anonymous"
    ></script>
    {% block js %}{% endblock %}
  </body>
</html>

app/templates/navigation.html
<!-- Navigation -->
<header class="p-3 text-bg-dark">
  <div class="container">
    <div
      class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start"
    >
      <ul
        class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0"
      >
        <li>
          <a
            href="{{ url_for('core.home') }}"
            class="nav-link px-2 text-secondary"
            >Home</a
          >
        </li>
      </ul>

      <div class="text-end">
        {% if current_user.is_authenticated %}
          <a href="{{ url_for('accounts.logout') }}"
            ><button type="button" class="btn btn-danger me-2">
              Logout
            </button></a
          >
        {% else %}
          <a href="{{ url_for('accounts.login') }}"
            ><button type="button" class="btn btn-outline-light me-2">
              Login
            </button></a
          >
          <a href="{{ url_for('accounts.register') }}"
            ><button type="button" class="btn btn-success">Sign up</button></a
          >
        {% endif %}
      </div>
    </div>
  </div>
</header>